### ISSUE TITLE
displays percentage as temperature 

### ISSUE THREAD

**Issue by ylw311** [narugit/smctemp#13] opened 2023-08-07 01:37 UTC
unsure if this is intentional?

Output when smctemp -c is ran
<img width="55" alt="image" src="https://github.com/narugit/smctemp/assets/61102300/9825e8a5-eceb-44a1-bb32-dcd5c83a2bc1">

**Comment by narugit** [comment] 2023-08-07 06:54
@ylw311 
Thank you for bringing this to my attention. 

I'd like to clarify that this behavior is actually related to the configuration of the zsh's `PROMPT_EOL_MARK` and is not caused by `smctemp`, so I would like to close this issue.

You can check from https://zsh.sourceforge.io/Doc/Release/Parameters.html#Parameters-Used-By-The-Shell
The default value is '%B%S%#%s%b', so if you don't want to show '%', you can set it `PROMPT_EOL_MARK=''`.

If you have any further questions or encounter any other issues, please don't hesitate to let me know.

**Closed by narugit** 2023-08-07 06:54 UTC
